SELECT 
CASE 
    WHEN G.Grade < 8 THEN NULL
    ELSE S.Name
END,
G.Grade, S.Marks
FROM Students AS S
JOIN Grades AS G
ON S.Marks BETWEEN G.Min_Mark AND G.Max_Mark
ORDER BY G.Grade DESC, S.Name ASC;

/*Or*/

SELECT STUDENTS.NAME, GRADES.GRADE, STUDENTS.MARKS FROM STUDENTS, GRADES WHERE STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK AND GRADES.GRADE >= 8 ORDER BY GRADES.GRADE DESC, STUDENTS.NAME ASC;

SELECT "NULL", GRADES.GRADE, STUDENTS.MARKS FROM STUDENTS, GRADES WHERE STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK AND GRADES.GRADE < 8 ORDER BY GRADES.GRADE DESC, STUDENTS.MARKS ASC;