SELECT ROUND(SQRT(POWER(MAX(LAT_N)-MIN(LAT_N),2)+POWER(MAX(LONG_W)-MIN(LONG_W),2)),4) FROM STATION;

/*Or*/

SELECT ROUND(SQRT((MAX(LAT_N)-MIN(LAT_N))*(MAX(LAT_N)-MIN(LAT_N))+(MAX(LONG_W)-MIN(LONG_W))*(MAX(LONG_W)-MIN(LONG_W))),4) FROM STATION;